apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-workflow
  # namespace: waficash-temporal
spec:
  selector:
    matchLabels:
      app: hello-workflow
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-workflow
    spec:
      containers:

      # worker container
      - name: hello-workflow-worker
        image: damola12345/hello-workflow-worker:latest
        env:
        - name: TEMPORAL_ADDRESS
          value: temporal-frontend:7233

      # starter container
      - name: hello-workflow-starter
        image: damola12345/hello-workflow-starter:latest
        env:
        - name: TEMPORAL_ADDRESS
          value: temporal-frontend:7233